# Generated by Django 2.2.7 on 2019-12-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type_f_p',
            field=models.BooleanField(default=False),
        ),
    ]
