# Generated by Django 3.0.2 on 2020-02-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191206_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='type_f_p',
            new_name='Premium',
        ),
    ]
