# Generated by Django 3.0.4 on 2020-03-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_contect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contect',
            new_name='contact',
        ),
    ]
