# Generated by Django 3.0.4 on 2020-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_blog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
