# Generated by Django 3.0.4 on 2020-03-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200314_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
