# Generated by Django 3.0.4 on 2020-03-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
