# Generated by Django 3.0.4 on 2020-03-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.TextField(),
        ),
    ]
