# Generated by Django 3.0.4 on 2020-03-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200314_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='username',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
