# Generated by Django 3.0.4 on 2020-03-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200315_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='blog1',
        ),
    ]
