# Generated by Django 3.0.4 on 2020-03-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200315_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
