# Generated by Django 3.0.4 on 2020-03-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_blog1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog1',
        ),
    ]
