# Generated by Django 3.0.4 on 2020-03-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
