# Generated by Django 3.0.4 on 2020-03-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20200315_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment1',
        ),
    ]
