# Generated by Django 3.0.4 on 2020-03-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
