# Generated by Django 3.0.4 on 2020-03-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_course_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_comment',
        ),
    ]
