# Generated by Django 3.0.4 on 2020-03-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_delete_course_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursecomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('idofcourse', models.IntegerField()),
            ],
        ),
    ]
