# Generated by Django 3.0.4 on 2020-03-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_coursecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog1',
        ),
    ]
