# Generated by Django 3.0.4 on 2020-03-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_blog1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
