# Generated by Django 3.0.4 on 2020-03-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
